[project]
name = "pyJIRAReminder"
version = "0.8.0"  # x-release-please-version
description = "A simple desktop application to remind you of your Jira tasks."
authors = [
    { name = "Yegor Sheremetiev", email = "iegor.sheremetiev@visteon.com" }
]
readme = "README.md"